openapi: 3.0.0
info:
  description: ''
  title: BookingConfirmation
  version: ''
servers: []
paths:
  /BookingConfirmation: {}
components:
  schemas:
    BookingConfirmation:
      description: ''
      type: object
      properties:
        bookingStatus:
          description: missing description
          type: string
          enum:
            - Confirmation
            - Cancellation
            - Update
            - Pending
        bookingParty:
          $ref: '#/components/schemas/BookingParty'
          description: ''
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
    BookingParty:
      description: ''
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Document:
      description: >-
        A collection of data for a piece of written, printed or electronic
        matter that provides information or evidence.
      type: object
      properties:
        originatorName:
          description: >-
            The proper name (human readable) of the entity that published this
            event.
          type: string
        originatorId:
          description: >-
            The party identification code (i.e. SCAC) of the organization
            publishing the event.
          type: string
        issue:
          description: >-
            A date, time, date time or other date time value for an issuance of
            this document.
          type: string
          format: date-time
      required:
        - originatorName
        - issue
    Party:
      description: >-
        An individual, a group, or a body having a role in a business function. 
        Party has a legal connotation in a business transaction.

        Corresponding EDIFACT element: 3035 - Party function code qualifier.
      type: object
      properties:
        name:
          description: 'A name, expressed as text, for this party.'
          type: string
        printedParty:
          description: The party name and address exactly as printed on the document.
          type: string
        registeredForVAT:
          description: 'VAT registration indicator. '
          type: boolean
        taxReference:
          description: Tax identification of the party.
          type: string
        partyRef:
          description: Reference which represents the party.
          type: string
        organizationId:
          description: 'Unique identifier of the party. '
          type: string
