openapi: 3.0.0
info:
  description: ''
  title: FeederBillOfLading
  version: ''
servers: []
paths:
  /FeederBillOfLading: {}
components:
  schemas:
    Carrier:
      type: object
      properties:
        carrierCode:
          description: SCAC code.
          type: string
        name:
          description: 'Carrier name. '
          type: string
        taxId:
          description: 'Carrier''''s tax identification. '
          type: string
      required:
        - carrierCode
        - name
    Consignee:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Consignment:
      type: object
      properties:
        departureDate:
          description: 'Date and time of departure. '
          type: string
          format: date-time
        serviceMode:
          allOf:
            - description: 'The scope of the consignment, such as CY-CY or SD-SD.'
            - $ref: '#/components/schemas/Text'
            - type: object
        transportEquipmentQuantity:
          description: >-
            A number of pieces of transport equipment, such as containers or
            similar unit load devices, in this consignment.
          type: number
        mainCarriageTransportMovement:
          items:
            $ref: '#/components/schemas/TransportMovement'
          type: array
        consignee:
          $ref: '#/components/schemas/Consignee'
        consignor:
          $ref: '#/components/schemas/Consignor'
        carrier:
          $ref: '#/components/schemas/Carrier'
        utilizedTransportEquipment:
          items:
            $ref: '#/components/schemas/TransportEquipment'
          type: array
        consignmentItems:
          items:
            $ref: '#/components/schemas/ConsignmentItem'
          type: array
          minItems: 1
        placeOfDelivery:
          $ref: '#/components/schemas/Location'
        portOfDischarge:
          $ref: '#/components/schemas/Location'
        placeOfReceipt:
          $ref: '#/components/schemas/Location'
        portOfLoading:
          $ref: '#/components/schemas/Location'
        placeOfPrecarriage:
          $ref: '#/components/schemas/Location'
        otherParties:
          items:
            $ref: '#/components/schemas/OtherParty'
          type: array
      required:
        - consignee
        - consignor
        - carrier
        - consignmentItems
    ConsignmentItem:
      type: object
      properties:
        information:
          description: >-
            Cargo description. Information, expressed as text, for this
            consignment item.
          type: string
        codeType:
          description: |-
            The cargo code type of consignment item. 
            https://service.unece.org/trade/untdid/d00a/tred/tred7143.htm
          type: string
          enum:
            - harmonizedSystem
            - stockKeepingUnit
            - purchaseOrder
            - cargoSpecificationNumber
            - vehicleIdentificationNumber
        codeValue:
          description: A code specifying a type of consignment item.
          type: string
        equipmentStuffing:
          items:
            $ref: '#/components/schemas/Stuffing'
          type: array
        grossWeight:
          items:
            $ref: '#/components/schemas/Weight'
          type: array
        transportPackages:
          $ref: '#/components/schemas/TransportPackage'
    Consignor:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Document:
      type: object
      properties:
        originatorName:
          description: >-
            The proper name (human readable) of the entity that published this
            event.
          type: string
        originatorId:
          description: >-
            The party identification code (i.e. SCAC) of the organization
            publishing the event.
          type: string
        issue:
          description: >-
            A date, time, date time or other date time value for an issuance of
            this document.
          type: string
          format: date-time
        placeOfIssue:
          $ref: '#/components/schemas/Location'
        original:
          $ref: '#/components/schemas/Location'
    FeederBillOfLading:
      type: object
      properties:
        documentName:
          allOf:
            - description: missing description
            - $ref: '#/components/schemas/Text'
            - type: object
        arrivalDate:
          allOf:
            - description: missing description
            - $ref: '#/components/schemas/DateTime'
            - type: object
      allOf:
        - $ref: '#/components/schemas/TransportDocument'
        - type: object
    Location:
      type: object
      properties:
        name:
          description: |-
            A name, expressed as text, of this logistics related location.
            Corresponding EDIFACT element: 3225 - Location name code.
          type: string
        UNLocode:
          description: >-
            United Nations Location Code (UNLOCODE) unique identifier for
            logistics related location. 
          type: string
        printedLocation:
          description: The location exactly as printed on the document.
          type: string
    OtherParty:
      type: object
      properties:
        partyRole:
          description: 'Type of party. '
          type: string
          enum:
            - exporter
            - importer
            - origin3PL
            - destination3PL
            - seller
            - buyer
            - exportCustomsBroker
            - importCustomsBroker
            - requestParty
            - buyersBank
            - sellersBank
            - insuranceProvider
            - oceanCarrier
            - transportServiceBuyer
            - transportServiceIntermediary
            - railOperator
            - truckOperator
            - bargeOperator
            - feederOperator
            - originMarineTerminal
            - destinationMarineTerminal
            - transhipmentTerminal
            - inlandTerminal
            - portCommunitySystem
            - exportAuthority
            - importAuthority
      allOf:
        - $ref: '#/components/schemas/Party'
        - type: object
    Party:
      type: object
      properties:
        name:
          description: 'A name, expressed as text, for this party.'
          type: string
        printedParty:
          description: The party name and address exactly as printed on the document.
          type: string
        registeredForVAT:
          description: 'VAT registration indicator. '
          type: boolean
    Seal:
      type: object
      properties:
        type:
          description: Description specifying the type of logistics seal.
          type: string
        identifier:
          description: A unique identifier for this logistics seal.
          type: string
    Stuffing:
      type: object
      properties:
        equipmentNumber:
          description: >-
            Unique identifier of the transport equipment in which cargo is
            stuffed. 
          type: string
    TransportDocument:
      type: object
      properties:
        shippedOnBoardDate:
          description: 'Date when the cargo was shipped on board. '
          type: string
          format: date-time
        billOfLadingNumber:
          description: 'Bill of lading number of the transport document. '
          type: string
        bookingNumber:
          items:
            description: 'Booking number(s). '
            type: string
          type: array
      allOf:
        - $ref: '#/components/schemas/Document'
        - type: object
        - $ref: '#/components/schemas/Consignment'
        - type: object
      required:
        - billOfLadingNumber
    TransportEquipment:
      type: object
      properties:
        equipmentNumber:
          allOf:
            - description: >-
                Unique identifier for this piece of transport equipment, printed
                physically on the equipment.
            - $ref: '#/components/schemas/Identifier'
            - type: object
        equipmentType:
          description: ISO 6346 size and type code (for example "45G1")
          type: string
        printedEquipmentType:
          description: >-
            The container size and type, as printed on the transport document
            (for example "40 DRY 9''6").
          type: string
        code:
          items:
            description: >-
              The harmonized system code specifying a type of loaded consignment
              item(s).
            type: string
          type: array
        usedCapacity:
          description: >-
            The code specifying the used capacity of this piece of transport
            equipment, such as full or empty.
          type: string
          enum:
            - full
            - empty
        seals:
          items:
            $ref: '#/components/schemas/Seal'
          type: array
        equipmentTareWeight:
          $ref: '#/components/schemas/Weight'
      required:
        - equipmentNumber
    TransportMeans:
      type: object
      properties:
        identification:
          description: >-
            An identifier of this logistics means of transport, such as the
            International Maritime Organization number of a vessel.
          type: string
        name:
          description: >-
            The name, expressed as text, of this logistics means of transport
            such as the vessel name.
          type: string
    TransportMovement:
      type: object
      properties:
        identification:
          description: >-
            To identify a journey of a means of transport, for example voyage
            number, flight number, trip number.
          type: string
        usedTransportMeans:
          $ref: '#/components/schemas/TransportMeans'
    TransportPackage:
      type: object
      properties:
        quantity:
          description: The number of logistics packages at this level.
          type: number
    Weight:
      type: object
      properties:
        value:
          allOf:
            - description: 'Numeric weight value. '
            - $ref: '#/components/schemas/Numeric'
            - type: object
        unit:
          description: Unit used for weight measurement.
          type: string
          enum:
            - kgs
            - lbs
    Text:
      type: object
      properties: {}
    DateTime:
      type: object
      properties: {}
    Numeric:
      type: object
      properties: {}
    Indicator:
      type: object
      properties: {}
    Identifier:
      type: object
      properties: {}
